version: '3.7'

services:

  redis:
    image: redis

  web:
    build:
      context: ./microblog/
    ports:
      - "8000:8000"
    links:
      - redis

  nginx:
    restart: always
    build: ./nginx/
    ports:
      - "8080:80"
    links:
      - web
